[project]
name = "advent-of-code"
version = "0.1.0"
description = "Advent of Code Solutions"
readme = "README.org"
requires-python = ">=3.13"
dependencies = [
    "hy>=1.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.8.1",
]
